### PR TITLE
Added js variable name and json integer data type check

### PR DESCRIPTION
**Pull request by demogorgorn**
Added json encode options for checking integer data type.

Added varName param. Variable name is needed in case when there is possibility to use more than one chart in page and it is planned to call these charts (modify their data) from js.

### CODE REVIEW

**Comment by demogorgorn** [comment]
Hello! If you're not interested in code modification please inform me! So I'll fork project and fix the issue. Possibility to use more than one chart in page is very important!

**Comment by miloschuman** [comment]
@demogorgorn, I'll pull your changes now, but I have reservations about c20814b. While 99% of cases may merit encoding numerical strings as numbers, I do not want to preclude a developer from using numerical strings in the few cases when they are needed/desired. Anyway, sorry for the delay, but I am working on the next release, which will include a helper for preprocessing data, so this will hopefully be a non-issue shortly.

**Comment by demogorgorn** [comment]
Thank you! About https://github.com/miloschuman/yii2-highcharts/commit/c20814b3727ea731aefd46ffb7252727bde7d91c I can say following: when i tried to post numerical (double) data to highchart it was converted to string. Anyway the most important thing was using multiple charts on page!

**Comment by drps** [comment]
as i can see there is no JSON_NUMERIC_CHECK options parameter since e9805dab4eb78b33be597d5d07808c6a4cc92d6d
is it possible to add configuration parameters for options passed to BaseJson::encode($value, $options = 320)?

**Pull request merged**
